version: '3.1'
services:
  postgres_db:
    image: postgres:13.1-alpine
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'taskmanagement'
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db: